# Generated by Django 5.2.10 on 2026-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вигадане імя для адмінів', max_length=255, verbose_name="Ім'я проксі")),
                ('host', models.CharField(max_length=255, verbose_name='Хост проксі')),
                ('port', models.PositiveIntegerField(verbose_name='Порт проксі')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Країна проксі')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Штат/Область проксі')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто проксі')),
                ('zip', models.CharField(blank=True, max_length=20, null=True, verbose_name='Поштовий індекс проксі')),
                ('isp', models.CharField(blank=True, max_length=100, null=True, verbose_name='ISP проксі')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('dead', 'Мертвий'), ('error', 'Помилка')], default='active', max_length=20, verbose_name='Статус проксі')),
                ('fail_count', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість помилок')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання перевірка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний для використання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Проксі',
                'verbose_name_plural': 'Проксі',
                'ordering': ['-created_at'],
            },
        ),
    ]
