# Generated by Django 6.0.2 on 2026-02-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0002_alter_proxy_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NineProxyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Країна (код, напр. US, VN)",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Штат/Область",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Місто"
                    ),
                ),
                (
                    "zip",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Поштовий індекс",
                    ),
                ),
                (
                    "isp",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ISP"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Останнє оновлення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування 9Proxy",
                "verbose_name_plural": "Налаштування 9Proxy",
            },
        ),
    ]
