# Generated by Django 6.0.2 on 2026-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxies", "0003_nineproxyconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NineProxyConfig",
        ),
        migrations.AddField(
            model_name="proxy",
            name="is_9proxy",
            field=models.BooleanField(
                default=False,
                help_text="Якщо увімкнено, хост та порт будуть отримані автоматично через 9Proxy API",
                verbose_name="Це динамічне 9Proxy",
            ),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="host",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Хост проксі"
            ),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="port",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Порт проксі"
            ),
        ),
    ]
