# Generated by Django 6.0.3 on 2026-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0004_delete_nineproxyconfig_proxy_is_9proxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, help_text='Якщо проксі вимагає аутентифікації, вкажіть пароль', max_length=255, null=True, verbose_name='Пароль проксі'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, help_text="Якщо проксі вимагає аутентифікації, вкажіть ім'я користувача", max_length=255, null=True, verbose_name='Користувач проксі'),
        ),
    ]
