# Generated by Django 6.0.3 on 2026-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0005_proxy_password_proxy_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Прокси', 'verbose_name_plural': 'Прокси'},
        ),
        migrations.AlterField(
            model_name='proxy',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='fail_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество ошибок'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хост прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='is_9proxy',
            field=models.BooleanField(default=False, help_text='Если включено, хост и порт будут получены автоматически через 9Proxy API', verbose_name='Это динамическое 9Proxy'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен для использования'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='isp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ISP прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='name',
            field=models.CharField(help_text='Вымышленное имя для админов', max_length=255, verbose_name='Имя прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, help_text='Если прокси требует аутентификации, укажите пароль', max_length=255, null=True, verbose_name='Пароль прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Штат/Область прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('dead', 'Мертвый'), ('error', 'Ошибка')], default='active', max_length=20, verbose_name='Статус прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, help_text='Если прокси требует аутентификации, укажите имя пользователя', max_length=255, null=True, verbose_name='Пользователь прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс прокси'),
        ),
    ]
