# Generated by Django 5.2.10 on 2026-02-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва завдання')),
                ('keywords', models.JSONField(verbose_name='Ключові слова')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'В процесі'), ('done', 'Done'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=20, verbose_name='Статус завдання')),
                ('theads', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість потоків')),
                ('use_uniqueness', models.BooleanField(default=False, verbose_name='Використовувати унікальність')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва таблиці результатів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата початку')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Повідомлення про помилку')),
            ],
            options={
                'verbose_name': 'Завдання парсингу',
                'verbose_name_plural': 'Завдання парсингу',
                'ordering': ['-created_at'],
            },
        ),
    ]
