# Generated by Django 5.2.10 on 2026-02-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsetask',
            old_name='theads',
            new_name='threads',
        ),
    ]
