# Generated by Django 5.2.10 on 2026-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_theads_parsetask_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsetask',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID Celery задачі'),
        ),
        migrations.AddField(
            model_name='parsetask',
            name='processed_urls',
            field=models.PositiveIntegerField(default=0, verbose_name='Оброблено URL'),
        ),
        migrations.AddField(
            model_name='parsetask',
            name='total_urls',
            field=models.PositiveIntegerField(default=0, verbose_name='Всього URL'),
        ),
    ]
