# Generated by Django 5.2.10 on 2026-02-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_parsetask_celery_task_id_parsetask_processed_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsetask',
            name='processed_urls',
            field=models.PositiveIntegerField(default=0, verbose_name='Оброблено Пінів'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='total_urls',
            field=models.PositiveIntegerField(default=0, verbose_name='Зібрано Пінів'),
        ),
    ]
