# Generated by Django 6.0.2 on 2026-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_parsetask_processed_urls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsetask",
            name="auto_sheet_name",
            field=models.BooleanField(
                default=True, verbose_name="Автоматична назва таблиці"
            ),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="keywords",
            field=models.JSONField(default=list, verbose_name="Ключові слова"),
        ),
        migrations.AlterField(
            model_name="parsetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує"),
                    ("running", "В процесі"),
                    ("done", "Виконано"),
                    ("error", "Помилка"),
                    ("stopped", "Зупинено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус завдання",
            ),
        ),
    ]
