# Generated by Django 6.0.2 on 2026-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_parsetask_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsetask',
            name='export_file',
            field=models.FileField(blank=True, null=True, upload_to='exports/'),
        ),
    ]
