# Generated by Django 6.0.2 on 2026-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_parsetask_export_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('running', 'В процесі'), ('uniqueness', 'Унікалізація'), ('done', 'Виконано'), ('error', 'Помилка'), ('stopped', 'Зупинено')], default='pending', max_length=20, verbose_name='Статус завдання'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='threads',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Кількість потоків'),
        ),
    ]
