# Generated by Django 6.0.2 on 2026-02-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_parsetask_status_alter_parsetask_threads'),
        ('uniqueness', '0004_uniquenessconfig_use_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsetask',
            name='uniqueness_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_task', to='uniqueness.uniquenessconfig', verbose_name='Конфіг унікалізації'),
        ),
    ]
