# Generated by Django 6.0.2 on 2026-02-19 14:41

import apps.tasks.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_parsetask_uniqueness_config'),
        ('uniqueness', '0005_alter_uniquenessconfig_use_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsetask',
            name='uniqueness_config',
            field=models.ForeignKey(blank=True, default=apps.tasks.models.get_default_uniqueness_config, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_task', to='uniqueness.uniquenessconfig', verbose_name='Конфіг унікалізації'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='use_uniqueness',
            field=models.BooleanField(default=True, verbose_name='Використовувати унікальність'),
        ),
    ]
