# Generated by Django 6.0.3 on 2026-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_parsetask_uniqueness_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('running', 'В процесі'), ('waiting_uniqueness', 'Очікує унікалізації'), ('uniqueness', 'Унікалізація'), ('done', 'Виконано'), ('error', 'Помилка'), ('stopped', 'Зупинено')], default='pending', max_length=20, verbose_name='Статус завдання'),
        ),
    ]
