# Generated by Django 6.0.2 on 2026-06-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_parsetask_uniqueness_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsetask',
            name='anotation_filter_1',
            field=models.TextField(blank=True, null=True, verbose_name='Фільтр анотації 1'),
        ),
        migrations.AddField(
            model_name='parsetask',
            name='anotation_filter_2',
            field=models.TextField(blank=True, null=True, verbose_name='Фільтр анотації 2'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('running', 'В процесі'), ('waiting_uniqueness', 'Очікує унікалізації'), ('uniqueness', 'Унікалізація'), ('done', 'Виконано'), ('error', 'Помилка'), ('stopped', 'Зупинено')], default='pending', max_length=20, verbose_name='Статус завдання'),
        ),
    ]
