# Generated by Django 6.0.2 on 2026-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_parsetask_anotation_filter_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsetask',
            name='anotation_filter_1',
            field=models.CharField(blank=True, null=True, verbose_name='Фільтр анотації 1'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='anotation_filter_2',
            field=models.CharField(blank=True, null=True, verbose_name='Фільтр анотації 2'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='threads',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кількість потоків'),
        ),
    ]
