# Generated by Django 6.0.2 on 2026-06-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_alter_parsetask_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPostConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_token",
                    models.UUIDField(
                        help_text="UUID токен з сервісу автопостингу",
                        verbose_name="Webhook токен",
                    ),
                ),
                (
                    "board_name",
                    models.CharField(
                        max_length=255, verbose_name="Назва дошки Pinterest"
                    ),
                ),
                (
                    "min_interval",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Мінімальний час між постами в хвилинах",
                        verbose_name="Мінімальний інтервал (хвилини)",
                    ),
                ),
                (
                    "max_interval",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Максимальний час між постами в хвилинах",
                        verbose_name="Максимальний інтервал (хвилини)",
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        default="https://example.com/?",
                        help_text="Наприклад: https://example.com/?",
                        max_length=500,
                        verbose_name="Базовий URL сайту",
                    ),
                ),
                (
                    "use_uniqueness",
                    models.BooleanField(
                        default=True, verbose_name="Унікалізувати перед постингом"
                    ),
                ),
                (
                    "groq_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Ключ для унікалізації через Groq",
                        max_length=255,
                        null=True,
                        verbose_name="Groq API ключ",
                    ),
                ),
                (
                    "groq_prompt",
                    models.TextField(
                        blank=True,
                        default="Uniquify the following Pinterest pin content. Return ONLY a JSON object with 'title' and 'description' keys.\n\nOriginal Title: {{title}}\nOriginal Description: {{description}}\nAlt Text: {{alt_text}}\nAnnotation: {{annotation}}\n\nCRITICAL RULES:\n1. Rewrite title and description to make them 100% unique, engaging, and clicking.\n2. Keep the EXACT SAME LANGUAGE as the input text (e.g. if input is Ukrainian, output Ukrainian).\n3. Return ONLY valid JSON, do not include markdown blocks like ```json, no explanations.",
                        help_text="Кастомний промпт для Groq API",
                        null=True,
                        verbose_name="Промпт для унікалізації",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Не активний"),
                            ("running", "Постинг"),
                            ("paused", "На паузі"),
                            ("completed", "Завершено"),
                            ("error", "Помилка"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="Статус автопостингу",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID Celery задачі автопостингу",
                    ),
                ),
                (
                    "posted_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Опубліковано пінів"
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(default=0, verbose_name="Всього пінів"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Повідомлення про помилку"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата початку постингу"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершення постингу"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopost_config",
                        to="tasks.parsetask",
                        verbose_name="Завдання",
                    ),
                ),
            ],
            options={
                "verbose_name": "Налаштування автопостингу",
                "verbose_name_plural": "Налаштування автопостингу",
            },
        ),
    ]
