# Generated by Django 6.0.2 on 2026-06-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_autopostconfig"),
        ("results", "0003_pinresult_local_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPostQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Заплановано на"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує"),
                            ("posted", "Опубліковано"),
                            ("failed", "Помилка"),
                            ("skipped", "Пропущено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Опубліковано"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Повідомлення про помилку"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Кількість спроб"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_items",
                        to="tasks.autopostconfig",
                        verbose_name="Конфігурація автопостингу",
                    ),
                ),
                (
                    "pin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_queue_items",
                        to="results.pinresult",
                        verbose_name="Пін",
                    ),
                ),
            ],
            options={
                "verbose_name": "Елемент черги автопостингу",
                "verbose_name_plural": "Черга автопостингу",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.AddIndex(
            model_name="autopostqueue",
            index=models.Index(
                fields=["status", "scheduled_at"], name="tasks_autop_status_7e3c98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autopostqueue",
            index=models.Index(
                fields=["config", "status"], name="tasks_autop_config__47b1e9_idx"
            ),
        ),
    ]
