# Generated by Django 6.0.2 on 2026-06-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_autopostqueue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autopostconfig",
            name="webhook_token",
            field=models.UUIDField(
                blank=True,
                help_text="UUID токен з сервісу автопостингу",
                null=True,
                verbose_name="Webhook токен",
            ),
        ),
    ]
