# Generated by Django 6.0.2 on 2026-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_alter_autopostconfig_webhook_token"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="parsetask",
            index=models.Index(
                fields=["-created_at"], name="tasks_parse_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parsetask",
            index=models.Index(
                fields=["status", "-created_at"], name="tasks_parse_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parsetask",
            index=models.Index(
                fields=["owner", "-created_at"], name="tasks_parse_owner_created_idx"
            ),
        ),
    ]
