# Generated by Django 6.0.3 on 2026-07-17 14:44

import apps.tasks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0004_alter_pinresult_options_alter_pinresult_alt_text_and_more'),
        ('tasks', '0015_parsetask_indexes'),
        ('uniqueness', '0006_alter_uniquenessconfig_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autopostconfig',
            options={'verbose_name': 'Настройка автопостинга', 'verbose_name_plural': 'Настройки автопостинга'},
        ),
        migrations.AlterModelOptions(
            name='autopostqueue',
            options={'ordering': ['scheduled_at'], 'verbose_name': 'Элемент очереди автопостинга', 'verbose_name_plural': 'Очередь автопостинга'},
        ),
        migrations.AlterModelOptions(
            name='parsetask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задание парсинга', 'verbose_name_plural': 'Задания парсинга'},
        ),
        migrations.RenameIndex(
            model_name='autopostqueue',
            new_name='tasks_autop_status_932fef_idx',
            old_name='tasks_autop_status_7e3c98_idx',
        ),
        migrations.RenameIndex(
            model_name='autopostqueue',
            new_name='tasks_autop_config__7179cc_idx',
            old_name='tasks_autop_config__47b1e9_idx',
        ),
        migrations.RenameIndex(
            model_name='parsetask',
            new_name='tasks_parse_created_aea694_idx',
            old_name='tasks_parse_created_idx',
        ),
        migrations.RenameIndex(
            model_name='parsetask',
            new_name='tasks_parse_status_9af3b5_idx',
            old_name='tasks_parse_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='parsetask',
            new_name='tasks_parse_owner_i_122923_idx',
            old_name='tasks_parse_owner_created_idx',
        ),
        migrations.AddField(
            model_name='parsetask',
            name='annotation_filter_words',
            field=models.CharField(blank=True, help_text='Слова через запятую, если аннотация не содержит эти слова, пин будет пропущен', max_length=255, null=True, verbose_name='Фильтр по аннотации'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='board_name',
            field=models.CharField(max_length=255, verbose_name='Название доски Pinterest'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Celery задачи автопостинга'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения постинга'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='Ключ для уникализации через Groq', max_length=255, null=True, verbose_name='Groq API ключ'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='groq_prompt',
            field=models.TextField(blank=True, default="Uniquify the following Pinterest pin content. Return ONLY a JSON object with 'title' and 'description' keys.\n\nOriginal Title: {{title}}\nOriginal Description: {{description}}\nAlt Text: {{alt_text}}\nAnnotation: {{annotation}}\n\nCRITICAL RULES:\n1. Rewrite title and description to make them 100% unique, engaging, and clicking.\n2. Keep the EXACT SAME LANGUAGE as the input text (e.g. if input is Ukrainian, output Ukrainian).\n3. Return ONLY valid JSON, do not include markdown blocks like ```json, no explanations.", help_text='Кастомный промпт для Groq API', null=True, verbose_name='Промпт для уникализации'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='max_interval',
            field=models.PositiveIntegerField(default=200, help_text='Максимальное время между постами в минутах', verbose_name='Максимальный интервал (минуты)'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='min_interval',
            field=models.PositiveIntegerField(default=100, help_text='Минимальное время между постами в минутах', verbose_name='Минимальный интервал (минуты)'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='posted_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Опубликовано пинов'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='site_url',
            field=models.URLField(default='https://example.com/?', help_text='Например: https://example.com/?', max_length=500, verbose_name='Базовый URL сайта'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала постинга'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='status',
            field=models.CharField(choices=[('idle', 'Не активен'), ('running', 'Постинг'), ('paused', 'На паузе'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='idle', max_length=20, verbose_name='Статус автопостинга'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autopost_config', to='tasks.parsetask', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего пинов'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='use_uniqueness',
            field=models.BooleanField(default=True, verbose_name='Уникализировать перед постингом'),
        ),
        migrations.AlterField(
            model_name='autopostconfig',
            name='webhook_token',
            field=models.UUIDField(blank=True, help_text='UUID токен из сервиса автопостинга', null=True, verbose_name='Webhook токен'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='tasks.autopostconfig', verbose_name='Конфигурация автопостинга'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_queue_items', to='results.pinresult', verbose_name='Пин'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, verbose_name='Запланировано на'),
        ),
        migrations.AlterField(
            model_name='autopostqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('posted', 'Опубликовано'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='auto_sheet_name',
            field=models.BooleanField(default=True, verbose_name='Автоматическое название таблицы'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID Celery задачи'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='export_file',
            field=models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='Файл экспорта'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='keywords',
            field=models.JSONField(default=list, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='processed_urls',
            field=models.PositiveIntegerField(default=0, verbose_name='Собрано Пинов'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'В процессе'), ('waiting_uniqueness', 'Ожидает уникализации'), ('uniqueness', 'Уникализация'), ('done', 'Выполнено'), ('error', 'Ошибка'), ('stopped', 'Остановлено')], default='pending', max_length=20, verbose_name='Статус задания'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название таблицы результатов'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='threads',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Количество потоков'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='total_urls',
            field=models.PositiveIntegerField(default=0, verbose_name='Найдено Пинов'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='uniqueness_config',
            field=models.ForeignKey(blank=True, default=apps.tasks.models.get_default_uniqueness_config, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_task', to='uniqueness.uniquenessconfig', verbose_name='Конфиг уникализации'),
        ),
        migrations.AlterField(
            model_name='parsetask',
            name='use_uniqueness',
            field=models.BooleanField(default=True, verbose_name='Использовать уникальность'),
        ),
    ]
