# Generated by Django 5.2.10 on 2026-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinterestAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вигадане імя для адмінів', max_length=255, verbose_name="Ім'я аккаунту")),
                ('cookies', models.JSONField(help_text='Pinterest cookies (експортовані з браузеру)', verbose_name='Cookies аккаунту')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('banned', 'Заблокований'), ('error', 'Помилка')], default='active', max_length=20, verbose_name='Статус аккаунту')),
                ('fail_count', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість помилок')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Останнє використання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний для використання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Pinterest аккаунт',
                'verbose_name_plural': 'Pinterest аккаунти',
                'ordering': ['-created_at'],
            },
        ),
    ]
