# Generated by Django 5.2.10 on 2026-02-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinterestaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='proxies.proxy', verbose_name='Проксі для аккаунту'),
        ),
    ]
