# Generated by Django 6.0.2 on 2026-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_pinterestaccount_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinterestaccount",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User-Agent"),
        ),
    ]
