# Generated by Django 6.0.3 on 2026-07-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pinterestaccount_user_agent'),
        ('proxies', '0006_alter_proxy_options_alter_proxy_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinterestaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pinterest аккаунт', 'verbose_name_plural': 'Pinterest аккаунты'},
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='cookies',
            field=models.JSONField(help_text='Pinterest cookies (экспортированные из браузера)', verbose_name='Cookies аккаунта'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='fail_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество ошибок'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен для использования'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='name',
            field=models.CharField(help_text='Вымышленное имя для админов', max_length=255, verbose_name='Имя аккаунта'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='proxies.proxy', verbose_name='Прокси для аккаунта'),
        ),
        migrations.AlterField(
            model_name='pinterestaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('banned', 'Заблокирован'), ('error', 'Ошибка')], default='active', max_length=20, verbose_name='Статус аккаунта'),
        ),
    ]
