# Generated by Django 6.0.2 on 2026-02-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_pinterestaccount_id"),
        ("tasks", "0005_parsetask_auto_sheet_name_alter_parsetask_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Повідомлення")),
                (
                    "level",
                    models.CharField(
                        default="ERROR", max_length=20, verbose_name="Рівень"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.pinterestaccount",
                        verbose_name="Аккаунт",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="tasks.parsetask",
                        verbose_name="Завдання",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог помилок",
                "verbose_name_plural": "Логи помилок",
                "ordering": ["-created_at"],
            },
        ),
    ]
