# Generated by Django 6.0.3 on 2026-07-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('tasks', '0015_parsetask_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог ошибок', 'verbose_name_plural': 'Логи ошибок'},
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='level',
            field=models.CharField(default='ERROR', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tasks.parsetask', verbose_name='Задание'),
        ),
    ]
