# Generated by Django 5.2.10 on 2026-02-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniquenessConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('openai_api_key', models.CharField(max_length=255, verbose_name='OpenAI API key')),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='OpenAI model')),
                ('max_tokens_title', models.PositiveSmallIntegerField(default=100, verbose_name='Максимальна кількіть токенів для title')),
                ('max_tokens_description', models.PositiveSmallIntegerField(default=400, verbose_name='Максимальна кількіть токенів для desctription')),
                ('temperature', models.FloatField(default=1.0)),
                ('prompt_template', models.TextField(help_text='Доступні змінні:\n{{title}}, {{description}}, {{alt_text}}, {{annotation}}, {{domain}}', verbose_name='Промпт')),
                ('use_title', models.BooleanField(default=True)),
                ('use_description', models.BooleanField(default=True)),
                ('use_alt_text', models.BooleanField(default=True)),
                ('use_annotation', models.BooleanField(default=True)),
                ('use_domain', models.BooleanField(default=False)),
                ('max_requests_per_minute', models.PositiveSmallIntegerField(default=450, verbose_name='Максимальна кількість запитів за хвилину')),
                ('max_workers', models.PositiveSmallIntegerField(default=5, verbose_name='Кількість потококів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата збереження')),
            ],
            options={
                'verbose_name': 'Унікалізація',
                'verbose_name_plural': 'Унікалізація',
            },
        ),
    ]
