# Generated by Django 6.0.2 on 2026-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uniqueness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniquenessconfig",
            name="use_image_url",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="uniquenessconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="uniquenessconfig",
            name="prompt_template",
            field=models.TextField(
                help_text="Доступні змінні:\n{{title}}, {{description}}, {{alt_text}}, {{annotation}}, {{domain}}, {{image_url}}",
                verbose_name="Промпт",
            ),
        ),
    ]
