# Generated by Django 6.0.2 on 2026-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uniqueness", "0002_uniquenessconfig_use_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniquenessconfig",
            name="prompt_template",
            field=models.TextField(
                default="Uniquify the following Pinterest pin content. Return ONLY a JSON object with 'title' and 'description' keys.\n\nOriginal Title: {{title}}\nOriginal Description: {{description}}\nAlt Text: {{alt_text}}\nAnnotation: {{annotation}}\n",
                help_text="Доступні змінні:\n{{title}}, {{description}}, {{alt_text}}, {{annotation}}, {{domain}}, {{image_url}}",
                verbose_name="Промпт",
            ),
        ),
    ]
