# Generated by Django 6.0.2 on 2026-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueness', '0003_alter_uniquenessconfig_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquenessconfig',
            name='use_keyword',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='prompt_template',
            field=models.TextField(default="Uniquify the following Pinterest pin content. Return ONLY a JSON object with 'title' and 'description' keys.\n\nOriginal Title: {{title}}\nOriginal Description: {{description}}\nAlt Text: {{alt_text}}\nAnnotation: {{annotation}}\n", help_text='Доступні змінні:\n{{title}}, {{description}}, {{alt_text}}, {{annotation}}, {{domain}}, {{image_url}}, {{keyword}}', verbose_name='Промпт'),
        ),
    ]
