# Generated by Django 6.0.2 on 2026-02-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueness', '0004_uniquenessconfig_use_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_keyword',
            field=models.BooleanField(default=True),
        ),
    ]
