# Generated by Django 6.0.3 on 2026-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueness', '0005_alter_uniquenessconfig_use_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquenessconfig',
            options={'verbose_name': 'Уникализация', 'verbose_name_plural': 'Уникализация'},
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='max_requests_per_minute',
            field=models.PositiveSmallIntegerField(default=450, verbose_name='Максимальное количество запросов в минуту'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='max_tokens_description',
            field=models.PositiveSmallIntegerField(default=400, verbose_name='Максимальное количество токенов для описания'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='max_tokens_title',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Максимальное количество токенов для заголовка'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='max_workers',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Количество потоков'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='model',
            field=models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='OpenAI модель'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='openai_api_key',
            field=models.CharField(max_length=255, verbose_name='OpenAI API ключ'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='prompt_template',
            field=models.TextField(default="Uniquify the following Pinterest pin content. Return ONLY a JSON object with 'title' and 'description' keys.\n\nOriginal Title: {{title}}\nOriginal Description: {{description}}\nAlt Text: {{alt_text}}\nAnnotation: {{annotation}}\n", help_text='Доступные переменные:\n{{title}}, {{description}}, {{alt_text}}, {{annotation}}, {{domain}}, {{image_url}}, {{keyword}}', verbose_name='Промпт'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='temperature',
            field=models.FloatField(default=1.0, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_alt_text',
            field=models.BooleanField(default=True, verbose_name='Использовать Alt текст'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_annotation',
            field=models.BooleanField(default=True, verbose_name='Использовать аннотацию'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_description',
            field=models.BooleanField(default=True, verbose_name='Использовать описание'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_domain',
            field=models.BooleanField(default=False, verbose_name='Использовать домен'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_image_url',
            field=models.BooleanField(default=False, verbose_name='Использовать URL изображения'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_keyword',
            field=models.BooleanField(default=True, verbose_name='Использовать ключевое слово'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='use_title',
            field=models.BooleanField(default=True, verbose_name='Использовать заголовок'),
        ),
    ]
