# Generated by Django 6.1 on 2026-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueness', '0005_alter_uniquenessconfig_use_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquenessconfig',
            name='model',
        ),
        migrations.AddField(
            model_name='uniquenessconfig',
            name='model_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (gpt-4o-mini)'), ('dashscope', 'DashScope (qwen3.7-flash)')], default='openai', max_length=20, verbose_name='Провайдер модели'),
        ),
        migrations.AddField(
            model_name='uniquenessconfig',
            name='name',
            field=models.CharField(default='Default Config', max_length=255, verbose_name='Название конфигурации'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='openai_api_key',
            field=models.CharField(help_text='OpenAI API ключ или DashScope API ключ (DASHSCOPE_API_KEY)', max_length=255, verbose_name='API ключ'),
        ),
    ]
