# Generated by Django 6.1 on 2026-09-08 08:37

from django.db import migrations


def drop_model_column(apps, schema_editor):
    """Manually drop the model column if it still exists"""
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='uniqueness_uniquenessconfig'
            AND column_name='model';
        """)
        if cursor.fetchone():
            # Column exists, drop it
            cursor.execute('ALTER TABLE uniqueness_uniquenessconfig DROP COLUMN model;')


def reverse_drop(apps, schema_editor):
    """We can't reverse this operation safely"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueness', '0006_remove_uniquenessconfig_model_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_model_column, reverse_drop),
    ]
