# Generated by Django 6.1 on 2026-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueness', '0007_fix_model_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='max_requests_per_minute',
            field=models.PositiveSmallIntegerField(default=450, help_text='OpenAI: 450-500, DashScope (qwen): 10000-14000', verbose_name='Максимальна кількість запитів за хвилину'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='max_workers',
            field=models.PositiveSmallIntegerField(default=5, help_text='Рекомендовано: OpenAI 5-10, DashScope 50-100', verbose_name='Кількість потоків'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='model_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (gpt-5-nano) - 450 req/min'), ('dashscope', 'DashScope (qwen3.7-flash) - 15000 req/min'), ('omniroute', 'OmniRoute')], default='openai', max_length=20, verbose_name='Провайдер модели'),
        ),
        migrations.AlterField(
            model_name='uniquenessconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Ключ OpenAI або DashScope. Для OmniRoute залиште порожнім: ключ береться з .env.', max_length=255, verbose_name='API ключ'),
        ),
    ]
