# Generated by Django 6.1 on 2026-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueness', '0008_alter_uniquenessconfig_max_requests_per_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquenessconfig',
            name='omniroute_model',
            field=models.CharField(blank=True, default='', help_text='Лише для OmniRoute, наприклад kr/claude-sonnet-4.5. Якщо порожньо — використовується OMNIROUTE_MODEL із .env.', max_length=255, verbose_name='Модель OmniRoute'),
        ),
    ]
